services:
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db 
        
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    hostname: rabbitmq
  
#  play.catalog.service:
#    image: play.catalog.service
#    build:
#      context: .
#      dockerfile: ./Play.Catalog.Service/Dockerfile

#  play.inventory.service:
#    image: play.inventory.service
#    build:
#      context: .
#      dockerfile: Play.Inventory.Service/Dockerfile


volumes:
  mongodb-data:
  rabbitmq-data:

networks:
  default:
